# Generated by Django 3.1 on 2020-11-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programme',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='form',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='house',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='programme',
        ),
    ]
