# Generated by Django 3.1 on 2020-11-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20201017_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='gender',
        ),
    ]
