# Generated by Django 3.1 on 2020-11-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_position_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='house',
        ),
    ]
