# Generated by Django 3.1 on 2020-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('is_programme', models.BooleanField(default=False)),
                ('is_department', models.BooleanField(default=False)),
                ('is_house', models.BooleanField(default=False)),
                ('is_form', models.BooleanField(default=False)),
                ('closing_time', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
