# Generated by Django 3.1 on 2020-11-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='is_form',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='is_house',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='is_programme',
        ),
    ]
